
USE mysql;
DESCRIBE customers;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, 
       COUNT(*) as customer_count,
       ROUND(SUM(`purchase_amount`), 0) as total_revenue
FROM customers
GROUP BY gender
ORDER BY total_revenue DESC;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, `purchase_amount` as purchase_amount
FROM customers
WHERE discount_applied = 'Yes' 
  AND `purchase_amount` >= (
      SELECT AVG(`purchase_amount`) FROM customers
  )
ORDER BY purchase_amount DESC;

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) 'avg_rating'
from customers group by item_purchased
order by 'avg_rating' desc 
limit 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(AVG(`purchase_amount`),2) avg_purchase
FROM customers WHERE shipping_type IN('Standard','Express') 
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT subscription_status, COUNT(*) customers, 
ROUND(AVG(`purchase_amount`),2) avg_spend
FROM customers GROUP BY subscription_status;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
       ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),1) pct
FROM customers 
GROUP BY item_purchased ORDER BY pct DESC LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
SELECT CASE
 WHEN previous_purchases<=1 THEN 'New'
 WHEN previous_purchases<=10 THEN 'Returning' 
 ELSE 'Loyal' END segment, COUNT(*) customers
FROM customers GROUP BY segment ORDER BY segment;

-- Q8. What are the top 3 most purchased products within each category?
WITH ranked_items AS (
  SELECT category, item_purchased, COUNT(*) orders,
         ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) as `rank`
  FROM customers 
  GROUP BY category, item_purchased
)
SELECT * FROM ranked_items WHERE `rank` <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases)
-- also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;
--------------------------------------------------------------------------
-- Create age_group column in MySQL
ALTER TABLE customers 
ADD COLUMN age_group VARCHAR(20);

-- Populate it (matches your notebook exactly)
UPDATE customers SET age_group = 
    CASE 
        WHEN age <= 32 THEN 'young_adult'
        WHEN age <= 44 THEN 'adult' 
        WHEN age <= 57 THEN 'middle_aged'
        ELSE 'senior'
    END;

-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customers  -- Fixed table name
GROUP BY age_group
ORDER BY total_revenue DESC;


